package commentchecker

import (
	"strings"
	"testing"
)

func TestCheckLinePraise(t *testing.T) {
	r := CheckLine(1, "// Great function!", PolicyDeny)
	if r == nil {
		t.Fatal("expected result for praise comment")
	}
	if r.Category != "praise" {
		t.Errorf("category = %s, want praise", r.Category)
	}
	if r.Action != PolicyDeny {
		t.Errorf("action = %s, want deny", r.Action)
	}
}

func TestCheckLineRestating(t *testing.T) {
	r := CheckLine(5, "// This function does the thing", PolicyDeny)
	if r == nil {
		t.Fatal("expected result for restating comment")
	}
	if r.Category != "restating" {
		t.Errorf("category = %s, want restating", r.Category)
	}
}

func TestCheckLineAttribution(t *testing.T) {
	r := CheckLine(3, "// Generated by AI", PolicyDeny)
	if r == nil {
		t.Fatal("expected result for AI attribution")
	}
	if r.Category != "attribution" {
		t.Errorf("category = %s, want attribution", r.Category)
	}
}

func TestCheckLineFiller(t *testing.T) {
	r := CheckLine(10, "// Note: this is important", PolicyWarn)
	if r == nil {
		t.Fatal("expected result for filler comment")
	}
	if r.Category != "filler" {
		t.Errorf("category = %s, want filler", r.Category)
	}
}

func TestCheckLineValidComment(t *testing.T) {
	r := CheckLine(1, "// See RFC 1234 for the protocol spec", PolicyDeny)
	if r != nil {
		t.Errorf("valid comment should not be flagged: %v", r)
	}
}

func TestCheckLineNoComment(t *testing.T) {
	r := CheckLine(1, "func main() {", PolicyDeny)
	if r != nil {
		t.Errorf("line without comment should return nil")
	}
}

func TestCheckLineEndOfBlock(t *testing.T) {
	r := CheckLine(20, "// end of function", PolicyDeny)
	if r == nil {
		t.Fatal("expected result for end-of-block comment")
	}
}

func TestCheckContent(t *testing.T) {
	content := `package main

// Great implementation!
func add(a, b int) int {
    // This function returns the sum
    return a + b
}
`
	results := CheckContent(content, PolicyDeny)
	if len(results) < 2 {
		t.Errorf("expected at least 2 results, got %d", len(results))
	}
}

func TestCheckContentAllowPolicy(t *testing.T) {
	content := "// Great function!\nfunc main() {}\n"
	results := CheckContent(content, PolicyAllow)
	if len(results) != 0 {
		t.Errorf("allow policy should return no results, got %d", len(results))
	}
}

func TestShouldDeny(t *testing.T) {
	results := []Result{
		{Line: 1, Action: PolicyDeny},
	}
	if !ShouldDeny(results) {
		t.Error("should deny when any result has deny action")
	}

	results = []Result{
		{Line: 1, Action: PolicyWarn},
	}
	if ShouldDeny(results) {
		t.Error("should not deny when no result has deny action")
	}
}

func TestFormatResults(t *testing.T) {
	results := []Result{
		{Line: 5, Comment: "// Great!", Category: "praise", Reason: "test"},
	}
	s := FormatResults(results)
	if !strings.Contains(s, "line 5") {
		t.Error("format should contain line number")
	}
	if !strings.Contains(s, "praise") {
		t.Error("format should contain category")
	}
}

func TestFormatResultsEmpty(t *testing.T) {
	s := FormatResults(nil)
	if s != "" {
		t.Errorf("empty results should return empty string, got %s", s)
	}
}

func TestExtractCommentLineComment(t *testing.T) {
	c := extractComment("code here // comment")
	if c != "// comment" {
		t.Errorf("got %q, want // comment", c)
	}
}

func TestExtractCommentHashComment(t *testing.T) {
	c := extractComment("# python comment")
	if c != "# python comment" {
		t.Errorf("got %q, want # python comment", c)
	}
}

func TestExtractCommentNoComment(t *testing.T) {
	c := extractComment("just code here")
	if c != "" {
		t.Errorf("got %q, want empty", c)
	}
}

func TestExtractCommentShebang(t *testing.T) {
	c := extractComment("#!/bin/bash")
	if c != "" {
		t.Errorf("shebang should not be treated as comment, got %q", c)
	}
}

func TestCheckLineIncrementPattern(t *testing.T) {
	r := CheckLine(5, "// Increment the counter", PolicyDeny)
	if r == nil {
		t.Fatal("expected result for increment pattern")
	}
	if r.Category != "restating" {
		t.Errorf("category = %s, want restating", r.Category)
	}
}

func TestCheckLineHelperPattern(t *testing.T) {
	r := CheckLine(3, "// This is a helper function", PolicyDeny)
	if r == nil {
		t.Fatal("expected result for helper pattern")
	}
}
